#pragma kernel ExternalForces
#pragma kernel UpdatePositions

#include "./FluidMaths2D.hlsl"


static const int NumThreads = 256;
// Buffers
RWStructuredBuffer<float2> Positions;
RWStructuredBuffer<float2> Velocities;

// Settings
const uint numParticles;
const float gravity;
const float deltaTime;
const float collisionDamping;
const float2 boundsSize;

float2 ExternalForces(float2 pos, float2 velocity)
{
    return float2(0, -gravity);
}

void HandleCollisions(uint particleIndex)
{
    float2 pos = Positions[particleIndex];
    float2 vel = Velocities[particleIndex];

    // Keep particle inside bounds
    const float2 halfSize = boundsSize * 0.5;
    float2 edgeDst = halfSize - abs(pos);

    if (edgeDst.x <= 0)
    {
        pos.x = halfSize.x * sign(pos.x);
        vel.x *= -1 * collisionDamping;
    }
    if (edgeDst.y <= 0)
    {
        pos.y = halfSize.y * sign(pos.y);
        vel.y *= -1 * collisionDamping;
    }
    Positions[particleIndex] = pos;
    Velocities[particleIndex] = vel;
}

[numthreads(NumThreads,1,1)]
void ExternalForces(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= numParticles) return;

    Velocities[id.x] += ExternalForces(Positions[id.x], Velocities[id.x]) * deltaTime;
}

[numthreads(NumThreads, 1, 1)]
void UpdatePositions(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= numParticles) return;

    Positions[id.x] += Velocities[id.x] * deltaTime;
    HandleCollisions(id.x);
}
